/********************************************************************************
** Form generated from reading UI file 'finalsudokuqt.ui'
**
** Created: Sat Jan 5 13:54:58 2013
**      by: Qt User Interface Compiler version 4.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FINALSUDOKUQT_H
#define UI_FINALSUDOKUQT_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_finalsudokuqtClass
{
public:
    QWidget *centralWidget;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QLineEdit *lineEdit_10;
    QLineEdit *lineEdit_11;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_22;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLineEdit *lineEdit_26;
    QLineEdit *lineEdit_27;
    QLineEdit *lineEdit_28;
    QLineEdit *lineEdit_29;
    QLineEdit *lineEdit_30;
    QLineEdit *lineEdit_31;
    QLineEdit *lineEdit_32;
    QLineEdit *lineEdit_33;
    QLineEdit *lineEdit_34;
    QLineEdit *lineEdit_35;
    QLineEdit *lineEdit_36;
    QLineEdit *lineEdit_37;
    QLineEdit *lineEdit_38;
    QLineEdit *lineEdit_39;
    QLineEdit *lineEdit_40;
    QLineEdit *lineEdit_41;
    QLineEdit *lineEdit_42;
    QLineEdit *lineEdit_43;
    QLineEdit *lineEdit_44;
    QLineEdit *lineEdit_45;
    QLineEdit *lineEdit_46;
    QLineEdit *lineEdit_47;
    QLineEdit *lineEdit_48;
    QLineEdit *lineEdit_49;
    QLineEdit *lineEdit_50;
    QLineEdit *lineEdit_51;
    QLineEdit *lineEdit_52;
    QLineEdit *lineEdit_53;
    QLineEdit *lineEdit_54;
    QLineEdit *lineEdit_55;
    QLineEdit *lineEdit_56;
    QLineEdit *lineEdit_57;
    QLineEdit *lineEdit_58;
    QLineEdit *lineEdit_59;
    QLineEdit *lineEdit_60;
    QLineEdit *lineEdit_61;
    QLineEdit *lineEdit_62;
    QLineEdit *lineEdit_63;
    QLineEdit *lineEdit_64;
    QLineEdit *lineEdit_65;
    QLineEdit *lineEdit_66;
    QLineEdit *lineEdit_67;
    QLineEdit *lineEdit_68;
    QLineEdit *lineEdit_69;
    QLineEdit *lineEdit_70;
    QLineEdit *lineEdit_71;
    QLineEdit *lineEdit_72;
    QLineEdit *lineEdit_73;
    QLineEdit *lineEdit_74;
    QLineEdit *lineEdit_75;
    QLineEdit *lineEdit_76;
    QLineEdit *lineEdit_77;
    QLineEdit *lineEdit_78;
    QLineEdit *lineEdit_79;
    QLineEdit *lineEdit_80;
    QLineEdit *lineEdit_81;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;

    void setupUi(QMainWindow *finalsudokuqtClass)
    {
        if (finalsudokuqtClass->objectName().isEmpty())
            finalsudokuqtClass->setObjectName(QString::fromUtf8("finalsudokuqtClass"));
        finalsudokuqtClass->resize(399, 476);
        finalsudokuqtClass->setMinimumSize(QSize(399, 476));
        finalsudokuqtClass->setMaximumSize(QSize(399, 476));
        centralWidget = new QWidget(finalsudokuqtClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        lineEdit = new QLineEdit(centralWidget);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(10, 20, 41, 41));
        lineEdit_2 = new QLineEdit(centralWidget);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(50, 20, 41, 41));
        lineEdit_3 = new QLineEdit(centralWidget);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(90, 20, 41, 41));
        lineEdit_4 = new QLineEdit(centralWidget);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(140, 20, 41, 41));
        lineEdit_5 = new QLineEdit(centralWidget);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(180, 20, 41, 41));
        lineEdit_6 = new QLineEdit(centralWidget);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(220, 20, 41, 41));
        lineEdit_7 = new QLineEdit(centralWidget);
        lineEdit_7->setObjectName(QString::fromUtf8("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(270, 20, 41, 41));
        lineEdit_8 = new QLineEdit(centralWidget);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(310, 20, 41, 41));
        lineEdit_9 = new QLineEdit(centralWidget);
        lineEdit_9->setObjectName(QString::fromUtf8("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(350, 20, 41, 41));
        lineEdit_10 = new QLineEdit(centralWidget);
        lineEdit_10->setObjectName(QString::fromUtf8("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(10, 60, 41, 41));
        lineEdit_11 = new QLineEdit(centralWidget);
        lineEdit_11->setObjectName(QString::fromUtf8("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(50, 60, 41, 41));
        lineEdit_12 = new QLineEdit(centralWidget);
        lineEdit_12->setObjectName(QString::fromUtf8("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(90, 60, 41, 41));
        lineEdit_13 = new QLineEdit(centralWidget);
        lineEdit_13->setObjectName(QString::fromUtf8("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(140, 60, 41, 41));
        lineEdit_14 = new QLineEdit(centralWidget);
        lineEdit_14->setObjectName(QString::fromUtf8("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(180, 60, 41, 41));
        lineEdit_15 = new QLineEdit(centralWidget);
        lineEdit_15->setObjectName(QString::fromUtf8("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(220, 60, 41, 41));
        lineEdit_16 = new QLineEdit(centralWidget);
        lineEdit_16->setObjectName(QString::fromUtf8("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(270, 60, 41, 41));
        lineEdit_17 = new QLineEdit(centralWidget);
        lineEdit_17->setObjectName(QString::fromUtf8("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(310, 60, 41, 41));
        lineEdit_18 = new QLineEdit(centralWidget);
        lineEdit_18->setObjectName(QString::fromUtf8("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(350, 60, 41, 41));
        lineEdit_19 = new QLineEdit(centralWidget);
        lineEdit_19->setObjectName(QString::fromUtf8("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(10, 100, 41, 41));
        lineEdit_20 = new QLineEdit(centralWidget);
        lineEdit_20->setObjectName(QString::fromUtf8("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(50, 100, 41, 41));
        lineEdit_21 = new QLineEdit(centralWidget);
        lineEdit_21->setObjectName(QString::fromUtf8("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(90, 100, 41, 41));
        lineEdit_22 = new QLineEdit(centralWidget);
        lineEdit_22->setObjectName(QString::fromUtf8("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(140, 100, 41, 41));
        lineEdit_23 = new QLineEdit(centralWidget);
        lineEdit_23->setObjectName(QString::fromUtf8("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(180, 100, 41, 41));
        lineEdit_24 = new QLineEdit(centralWidget);
        lineEdit_24->setObjectName(QString::fromUtf8("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(220, 100, 41, 41));
        lineEdit_25 = new QLineEdit(centralWidget);
        lineEdit_25->setObjectName(QString::fromUtf8("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(270, 100, 41, 41));
        lineEdit_26 = new QLineEdit(centralWidget);
        lineEdit_26->setObjectName(QString::fromUtf8("lineEdit_26"));
        lineEdit_26->setGeometry(QRect(310, 100, 41, 41));
        lineEdit_27 = new QLineEdit(centralWidget);
        lineEdit_27->setObjectName(QString::fromUtf8("lineEdit_27"));
        lineEdit_27->setGeometry(QRect(350, 100, 41, 41));
        lineEdit_28 = new QLineEdit(centralWidget);
        lineEdit_28->setObjectName(QString::fromUtf8("lineEdit_28"));
        lineEdit_28->setGeometry(QRect(10, 150, 41, 41));
        lineEdit_29 = new QLineEdit(centralWidget);
        lineEdit_29->setObjectName(QString::fromUtf8("lineEdit_29"));
        lineEdit_29->setGeometry(QRect(50, 150, 41, 41));
        lineEdit_30 = new QLineEdit(centralWidget);
        lineEdit_30->setObjectName(QString::fromUtf8("lineEdit_30"));
        lineEdit_30->setGeometry(QRect(90, 150, 41, 41));
        lineEdit_31 = new QLineEdit(centralWidget);
        lineEdit_31->setObjectName(QString::fromUtf8("lineEdit_31"));
        lineEdit_31->setGeometry(QRect(140, 150, 41, 41));
        lineEdit_32 = new QLineEdit(centralWidget);
        lineEdit_32->setObjectName(QString::fromUtf8("lineEdit_32"));
        lineEdit_32->setGeometry(QRect(180, 150, 41, 41));
        lineEdit_33 = new QLineEdit(centralWidget);
        lineEdit_33->setObjectName(QString::fromUtf8("lineEdit_33"));
        lineEdit_33->setGeometry(QRect(220, 150, 41, 41));
        lineEdit_34 = new QLineEdit(centralWidget);
        lineEdit_34->setObjectName(QString::fromUtf8("lineEdit_34"));
        lineEdit_34->setGeometry(QRect(270, 150, 41, 41));
        lineEdit_35 = new QLineEdit(centralWidget);
        lineEdit_35->setObjectName(QString::fromUtf8("lineEdit_35"));
        lineEdit_35->setGeometry(QRect(310, 150, 41, 41));
        lineEdit_36 = new QLineEdit(centralWidget);
        lineEdit_36->setObjectName(QString::fromUtf8("lineEdit_36"));
        lineEdit_36->setGeometry(QRect(350, 150, 41, 41));
        lineEdit_37 = new QLineEdit(centralWidget);
        lineEdit_37->setObjectName(QString::fromUtf8("lineEdit_37"));
        lineEdit_37->setGeometry(QRect(10, 190, 41, 41));
        lineEdit_38 = new QLineEdit(centralWidget);
        lineEdit_38->setObjectName(QString::fromUtf8("lineEdit_38"));
        lineEdit_38->setGeometry(QRect(50, 190, 41, 41));
        lineEdit_39 = new QLineEdit(centralWidget);
        lineEdit_39->setObjectName(QString::fromUtf8("lineEdit_39"));
        lineEdit_39->setGeometry(QRect(90, 190, 41, 41));
        lineEdit_40 = new QLineEdit(centralWidget);
        lineEdit_40->setObjectName(QString::fromUtf8("lineEdit_40"));
        lineEdit_40->setGeometry(QRect(140, 190, 41, 41));
        lineEdit_41 = new QLineEdit(centralWidget);
        lineEdit_41->setObjectName(QString::fromUtf8("lineEdit_41"));
        lineEdit_41->setGeometry(QRect(180, 190, 41, 41));
        lineEdit_42 = new QLineEdit(centralWidget);
        lineEdit_42->setObjectName(QString::fromUtf8("lineEdit_42"));
        lineEdit_42->setGeometry(QRect(220, 190, 41, 41));
        lineEdit_43 = new QLineEdit(centralWidget);
        lineEdit_43->setObjectName(QString::fromUtf8("lineEdit_43"));
        lineEdit_43->setGeometry(QRect(270, 190, 41, 41));
        lineEdit_44 = new QLineEdit(centralWidget);
        lineEdit_44->setObjectName(QString::fromUtf8("lineEdit_44"));
        lineEdit_44->setGeometry(QRect(310, 190, 41, 41));
        lineEdit_45 = new QLineEdit(centralWidget);
        lineEdit_45->setObjectName(QString::fromUtf8("lineEdit_45"));
        lineEdit_45->setGeometry(QRect(350, 190, 41, 41));
        lineEdit_46 = new QLineEdit(centralWidget);
        lineEdit_46->setObjectName(QString::fromUtf8("lineEdit_46"));
        lineEdit_46->setGeometry(QRect(10, 230, 41, 41));
        lineEdit_47 = new QLineEdit(centralWidget);
        lineEdit_47->setObjectName(QString::fromUtf8("lineEdit_47"));
        lineEdit_47->setGeometry(QRect(50, 230, 41, 41));
        lineEdit_48 = new QLineEdit(centralWidget);
        lineEdit_48->setObjectName(QString::fromUtf8("lineEdit_48"));
        lineEdit_48->setGeometry(QRect(90, 230, 41, 41));
        lineEdit_49 = new QLineEdit(centralWidget);
        lineEdit_49->setObjectName(QString::fromUtf8("lineEdit_49"));
        lineEdit_49->setGeometry(QRect(140, 230, 41, 41));
        lineEdit_50 = new QLineEdit(centralWidget);
        lineEdit_50->setObjectName(QString::fromUtf8("lineEdit_50"));
        lineEdit_50->setGeometry(QRect(180, 230, 41, 41));
        lineEdit_51 = new QLineEdit(centralWidget);
        lineEdit_51->setObjectName(QString::fromUtf8("lineEdit_51"));
        lineEdit_51->setGeometry(QRect(220, 230, 41, 41));
        lineEdit_52 = new QLineEdit(centralWidget);
        lineEdit_52->setObjectName(QString::fromUtf8("lineEdit_52"));
        lineEdit_52->setGeometry(QRect(270, 230, 41, 41));
        lineEdit_53 = new QLineEdit(centralWidget);
        lineEdit_53->setObjectName(QString::fromUtf8("lineEdit_53"));
        lineEdit_53->setGeometry(QRect(310, 230, 41, 41));
        lineEdit_54 = new QLineEdit(centralWidget);
        lineEdit_54->setObjectName(QString::fromUtf8("lineEdit_54"));
        lineEdit_54->setGeometry(QRect(350, 230, 41, 41));
        lineEdit_55 = new QLineEdit(centralWidget);
        lineEdit_55->setObjectName(QString::fromUtf8("lineEdit_55"));
        lineEdit_55->setGeometry(QRect(10, 280, 41, 41));
        lineEdit_56 = new QLineEdit(centralWidget);
        lineEdit_56->setObjectName(QString::fromUtf8("lineEdit_56"));
        lineEdit_56->setGeometry(QRect(50, 280, 41, 41));
        lineEdit_57 = new QLineEdit(centralWidget);
        lineEdit_57->setObjectName(QString::fromUtf8("lineEdit_57"));
        lineEdit_57->setGeometry(QRect(90, 280, 41, 41));
        lineEdit_58 = new QLineEdit(centralWidget);
        lineEdit_58->setObjectName(QString::fromUtf8("lineEdit_58"));
        lineEdit_58->setGeometry(QRect(140, 280, 41, 41));
        lineEdit_59 = new QLineEdit(centralWidget);
        lineEdit_59->setObjectName(QString::fromUtf8("lineEdit_59"));
        lineEdit_59->setGeometry(QRect(180, 280, 41, 41));
        lineEdit_60 = new QLineEdit(centralWidget);
        lineEdit_60->setObjectName(QString::fromUtf8("lineEdit_60"));
        lineEdit_60->setGeometry(QRect(220, 280, 41, 41));
        lineEdit_61 = new QLineEdit(centralWidget);
        lineEdit_61->setObjectName(QString::fromUtf8("lineEdit_61"));
        lineEdit_61->setGeometry(QRect(270, 280, 41, 41));
        lineEdit_62 = new QLineEdit(centralWidget);
        lineEdit_62->setObjectName(QString::fromUtf8("lineEdit_62"));
        lineEdit_62->setGeometry(QRect(310, 280, 41, 41));
        lineEdit_63 = new QLineEdit(centralWidget);
        lineEdit_63->setObjectName(QString::fromUtf8("lineEdit_63"));
        lineEdit_63->setGeometry(QRect(350, 280, 41, 41));
        lineEdit_64 = new QLineEdit(centralWidget);
        lineEdit_64->setObjectName(QString::fromUtf8("lineEdit_64"));
        lineEdit_64->setGeometry(QRect(10, 320, 41, 41));
        lineEdit_65 = new QLineEdit(centralWidget);
        lineEdit_65->setObjectName(QString::fromUtf8("lineEdit_65"));
        lineEdit_65->setGeometry(QRect(50, 320, 41, 41));
        lineEdit_66 = new QLineEdit(centralWidget);
        lineEdit_66->setObjectName(QString::fromUtf8("lineEdit_66"));
        lineEdit_66->setGeometry(QRect(90, 320, 41, 41));
        lineEdit_67 = new QLineEdit(centralWidget);
        lineEdit_67->setObjectName(QString::fromUtf8("lineEdit_67"));
        lineEdit_67->setGeometry(QRect(140, 320, 41, 41));
        lineEdit_68 = new QLineEdit(centralWidget);
        lineEdit_68->setObjectName(QString::fromUtf8("lineEdit_68"));
        lineEdit_68->setGeometry(QRect(180, 320, 41, 41));
        lineEdit_69 = new QLineEdit(centralWidget);
        lineEdit_69->setObjectName(QString::fromUtf8("lineEdit_69"));
        lineEdit_69->setGeometry(QRect(220, 320, 41, 41));
        lineEdit_70 = new QLineEdit(centralWidget);
        lineEdit_70->setObjectName(QString::fromUtf8("lineEdit_70"));
        lineEdit_70->setGeometry(QRect(270, 320, 41, 41));
        lineEdit_71 = new QLineEdit(centralWidget);
        lineEdit_71->setObjectName(QString::fromUtf8("lineEdit_71"));
        lineEdit_71->setGeometry(QRect(310, 320, 41, 41));
        lineEdit_72 = new QLineEdit(centralWidget);
        lineEdit_72->setObjectName(QString::fromUtf8("lineEdit_72"));
        lineEdit_72->setGeometry(QRect(350, 320, 41, 41));
        lineEdit_73 = new QLineEdit(centralWidget);
        lineEdit_73->setObjectName(QString::fromUtf8("lineEdit_73"));
        lineEdit_73->setGeometry(QRect(10, 360, 41, 41));
        lineEdit_74 = new QLineEdit(centralWidget);
        lineEdit_74->setObjectName(QString::fromUtf8("lineEdit_74"));
        lineEdit_74->setGeometry(QRect(50, 360, 41, 41));
        lineEdit_75 = new QLineEdit(centralWidget);
        lineEdit_75->setObjectName(QString::fromUtf8("lineEdit_75"));
        lineEdit_75->setGeometry(QRect(90, 360, 41, 41));
        lineEdit_76 = new QLineEdit(centralWidget);
        lineEdit_76->setObjectName(QString::fromUtf8("lineEdit_76"));
        lineEdit_76->setGeometry(QRect(140, 360, 41, 41));
        lineEdit_77 = new QLineEdit(centralWidget);
        lineEdit_77->setObjectName(QString::fromUtf8("lineEdit_77"));
        lineEdit_77->setGeometry(QRect(180, 360, 41, 41));
        lineEdit_78 = new QLineEdit(centralWidget);
        lineEdit_78->setObjectName(QString::fromUtf8("lineEdit_78"));
        lineEdit_78->setGeometry(QRect(220, 360, 41, 41));
        lineEdit_79 = new QLineEdit(centralWidget);
        lineEdit_79->setObjectName(QString::fromUtf8("lineEdit_79"));
        lineEdit_79->setGeometry(QRect(270, 360, 41, 41));
        lineEdit_80 = new QLineEdit(centralWidget);
        lineEdit_80->setObjectName(QString::fromUtf8("lineEdit_80"));
        lineEdit_80->setGeometry(QRect(310, 360, 41, 41));
        lineEdit_81 = new QLineEdit(centralWidget);
        lineEdit_81->setObjectName(QString::fromUtf8("lineEdit_81"));
        lineEdit_81->setGeometry(QRect(350, 360, 41, 41));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(140, 410, 121, 31));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(10, 410, 75, 31));
        pushButton_3 = new QPushButton(centralWidget);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(310, 440, 75, 23));
        finalsudokuqtClass->setCentralWidget(centralWidget);

        retranslateUi(finalsudokuqtClass);
        QObject::connect(pushButton_3, SIGNAL(clicked()), finalsudokuqtClass, SLOT(close()));
        QObject::connect(pushButton, SIGNAL(clicked()), finalsudokuqtClass, SLOT(slove()));
        QObject::connect(pushButton_2, SIGNAL(clicked()), finalsudokuqtClass, SLOT(clear()));

        QMetaObject::connectSlotsByName(finalsudokuqtClass);
    } // setupUi

    void retranslateUi(QMainWindow *finalsudokuqtClass)
    {
        finalsudokuqtClass->setWindowTitle(QApplication::translate("finalsudokuqtClass", "Sudoku Solver", 0, QApplication::UnicodeUTF8));
        lineEdit->setText(QString());
        lineEdit_2->setText(QString());
        lineEdit_3->setText(QString());
        lineEdit_4->setText(QString());
        lineEdit_5->setText(QString());
        lineEdit_6->setText(QString());
        lineEdit_7->setText(QString());
        lineEdit_8->setText(QString());
        lineEdit_9->setText(QString());
        lineEdit_10->setText(QString());
        lineEdit_11->setText(QString());
        lineEdit_12->setText(QString());
        lineEdit_13->setText(QString());
        lineEdit_14->setText(QString());
        lineEdit_15->setText(QString());
        lineEdit_16->setText(QString());
        lineEdit_17->setText(QString());
        lineEdit_18->setText(QString());
        lineEdit_19->setText(QString());
        lineEdit_20->setText(QString());
        lineEdit_21->setText(QString());
        lineEdit_22->setText(QString());
        lineEdit_23->setText(QString());
        lineEdit_24->setText(QString());
        lineEdit_25->setText(QString());
        lineEdit_26->setText(QString());
        lineEdit_27->setText(QString());
        lineEdit_28->setText(QString());
        lineEdit_29->setText(QString());
        lineEdit_30->setText(QString());
        lineEdit_31->setText(QString());
        lineEdit_32->setText(QString());
        lineEdit_33->setText(QString());
        lineEdit_34->setText(QString());
        lineEdit_35->setText(QString());
        lineEdit_36->setText(QString());
        lineEdit_37->setText(QString());
        lineEdit_38->setText(QString());
        lineEdit_39->setText(QString());
        lineEdit_40->setText(QString());
        lineEdit_41->setText(QString());
        lineEdit_42->setText(QString());
        lineEdit_43->setText(QString());
        lineEdit_44->setText(QString());
        lineEdit_45->setText(QString());
        lineEdit_46->setText(QString());
        lineEdit_47->setText(QString());
        lineEdit_48->setText(QString());
        lineEdit_49->setText(QString());
        lineEdit_50->setText(QString());
        lineEdit_51->setText(QString());
        lineEdit_52->setText(QString());
        lineEdit_53->setText(QString());
        lineEdit_54->setText(QString());
        lineEdit_55->setText(QString());
        lineEdit_56->setText(QString());
        lineEdit_57->setText(QString());
        lineEdit_58->setText(QString());
        lineEdit_59->setText(QString());
        lineEdit_60->setText(QString());
        lineEdit_61->setText(QString());
        lineEdit_62->setText(QString());
        lineEdit_63->setText(QString());
        lineEdit_64->setText(QString());
        lineEdit_65->setText(QString());
        lineEdit_66->setText(QString());
        lineEdit_67->setText(QString());
        lineEdit_68->setText(QString());
        lineEdit_69->setText(QString());
        lineEdit_70->setText(QString());
        lineEdit_71->setText(QString());
        lineEdit_72->setText(QString());
        lineEdit_73->setText(QString());
        lineEdit_74->setText(QString());
        lineEdit_75->setText(QString());
        lineEdit_76->setText(QString());
        lineEdit_77->setText(QString());
        lineEdit_78->setText(QString());
        lineEdit_79->setText(QString());
        lineEdit_80->setText(QString());
        lineEdit_81->setText(QString());
        pushButton->setText(QApplication::translate("finalsudokuqtClass", "solve", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("finalsudokuqtClass", "clear", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("finalsudokuqtClass", "close", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class finalsudokuqtClass: public Ui_finalsudokuqtClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FINALSUDOKUQT_H
